import Post from '@/components/Home/Post/Post';
import Story from '@/components/Home/Story/story';
import Suggested from '@/components/Home/Suggested/Suggested';
import { Inter } from '@next/font/google';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Instagram</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className='w-full flex justify-center text-white'>
                <div className='flex w-[853px] justify-center pt-1'>
                    <div className='mr-16 flex-1 flex flex-col max-w-[470px]'>
                        <div className='h-3'/>
                        <Story />
                        <Post />
                    </div>
                    <Suggested />
                </div>
            </main>
        </>
    );
}
